import dotenv from 'dotenv';
dotenv.config();

export const {
  APP_PORT,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_ACTIVATE_SECRET,
  MOMO_PARTNER_CODE,
  MOMO_PARTNER_NAME,
  MOMO_ACCESS_KEY,
  MOMO_SECRET_KEY,
  MOMO_STORE_ID,
  MOMO_ENDPOINT,
  MOMO_REDIRECT_URL,
  MOMO_IPN_URL,
  VNP_TMN_CODE,
  VNP_HASH_SECRET,
  VNP_URL,
  VNP_RETURN_URL,
  EMAIL_USER,
  EMAIL_PASSWORD,
  SMTP_HOST,
  SMTP_PORT,
  FE_URL,
  BE_URL,
  INIT_MANAGER_SECRET,
} = process.env;
